<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="WorkloadsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=master;Integrated Security=True" SettingsObjectName="ProgramWithBD.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Groups">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Groups_Workloads" Member="Workloads" ThisKey="Id" OtherKey="GroupId" Type="Workloads" />
    </Type>
  </Table>
  <Table Name="dbo.Workloads" Member="Workloads">
    <Type Name="Workloads">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursLectures" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursPractice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Workloads_TeacherWorkloads" Member="TeacherWorkloads" ThisKey="Id" OtherKey="WorkloadId" Type="TeacherWorkloads" />
      <Association Name="Groups_Workloads" Member="Groups" ThisKey="GroupId" OtherKey="Id" Type="Groups" IsForeignKey="true" />
      <Association Name="Subjects_Workloads" Member="Subjects" ThisKey="SubjectId" OtherKey="Id" Type="Subjects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subjects" Member="Subjects">
    <Type Name="Subjects">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Subjects_Workloads" Member="Workloads" ThisKey="Id" OtherKey="SubjectId" Type="Workloads" />
    </Type>
  </Table>
  <Table Name="dbo.Teachers" Member="Teachers">
    <Type Name="Teachers">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Degree" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Post" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Expirience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Teachers_TeacherWorkloads" Member="TeacherWorkloads" ThisKey="Id" OtherKey="TeacherId" Type="TeacherWorkloads" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherWorkloads" Member="TeacherWorkloads">
    <Type Name="TeacherWorkloads">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Teachers_TeacherWorkloads" Member="Teachers" ThisKey="TeacherId" OtherKey="Id" Type="Teachers" IsForeignKey="true" />
      <Association Name="Workloads_TeacherWorkloads" Member="Workloads" ThisKey="WorkloadId" OtherKey="Id" Type="Workloads" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherWorkloadsView" Member="TeacherWorkloadsView">
    <Type Name="TeacherWorkloadsView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherLastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherFirstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherMiddlename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TracherDegree" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherPost" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherExperience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadHoursLectures" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadHoursPractice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WorkloadView" Member="WorkloadView">
    <Type Name="WorkloadView">
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoursLectures" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursPractice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="WorkloadYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetAllWorkloadByYear" Method="GetAllWorkloadByYear" IsComposable="true">
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllWorkloadByYearResult">
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Post" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Expirience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[HoursLections+HoursPractice]" Member="HoursLections_HoursPractice" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTeacherWorkload" Method="GetTeacherWorkload" IsComposable="true">
    <Parameter Name="tteacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTeacherWorkloadResult">
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="HoursLectures" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursPractice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>